disabled_rules:
  - trailing_whitespace
  - todo
  - line_length
  - identifier_name
  - cyclomatic_complexity
  - type_body_length
  - file_length
  - nesting
  - notification_center_detachment
  - function_body_length
  - unused_setter_value
included:
  - Sources/MapboxCoreNavigation
